@echo off
:: Télécharger et installer Poppler
echo Téléchargement de Poppler...
curl -L -o poppler.zip https://github.com/oschwartz10612/poppler-windows/releases/download/v24.07.0-0/Release-24.07.0-0.zip
echo Extraction de Poppler...
powershell -Command "Expand-Archive -Path Release-24.07.0-0.zip -DestinationPath C:poppler"
echo Ajout de Poppler au PATH...
setx PATH "%PATH%;C:\poppler-24.07.0\Library\bin"
echo Poppler installé avec succès !
