@echo off
:: Télécharger et installer Tesseract
echo Téléchargement de Tesseract...
curl -L -o tesseract.exe https://github.com/UB-Mannheim/tesseract/releases/download/v5.4.0.20240606/tesseract-ocr-w64-setup-5.4.0.20240606.exe
echo Installation de Tesseract...
start /wait tesseract.exe /S
echo Ajout de Tesseract au PATH...
setx PATH "%PATH%;C:\Program Files\Tesseract-OCR"
echo Tesseract installé avec succès !
